# Generated by Django 5.1.5 on 2025-01-31 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='activity',
            field=models.CharField(blank=True, choices=[('Kaya', 'Body'), ('Vedana', 'Feelings'), ('Citta', 'Mind'), ('Dhamma', 'Mind Objects')], max_length=10),
        ),
        migrations.AddField(
            model_name='experience',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
